### ISSUE TITLE
TypeError: zip argument #1 must support iteration

### ISSUE THREAD

**Issue by xiaoshengjun** [nusnlp/nbest-reranker#2]
hi, when I run the code ml2018 'train_reranker', the issue is called. Could you help me find where the problem is?

Loading source sentences
Traceback (most recent call last):
  File "/search/odin/liuxiaolong2019/mlconvgec2018-fairseq0.5/software/nbest-reranker/augmenter.py", line 63, in <module>
    augment(features, args.source_path, args.input_nbest_path, args.output_nbest_path)
  File "/search/odin/liuxiaolong2019/mlconvgec2018-fairseq0.5/software/nbest-reranker/augmenter.py", line 40, in augment
    for group, src_sent in zip(input_nbest, src_sents):
TypeError: zip argument #1 must support iteration

**Comment by Young1993** [comment]
> hi, when I run the code ml2018 'train_reranker', the issue is called. Could you help me find where the problem is?
> 
> Loading source sentences
> Traceback (most recent call last):
> File "/search/odin/liuxiaolong2019/mlconvgec2018-fairseq0.5/software/nbest-reranker/augmenter.py", line 63, in
> augment(features, args.source_path, args.input_nbest_path, args.output_nbest_path)
> File "/search/odin/liuxiaolong2019/mlconvgec2018-fairseq0.5/software/nbest-reranker/augmenter.py", line 40, in augment
> for group, src_sent in zip(input_nbest, src_sents):
> TypeError: zip argument #1 must support iteration

I met the same problem, while changing the code 
`for item in gruop.group`
the code is operating right, you can try or debug
